# Generated by Django 6.0.1 on 2026-02-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patient_created_by_patient_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
