# Generated by Django 6.0.1 on 2026-02-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_department_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(choices=[('Front Desk', 'Front Desk'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse')], on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='core.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Pediatrician', 'Pediatrician'), ('General Physician', 'General Physician')], max_length=100),
        ),
    ]
