# Generated by Django 6.0.1 on 2026-02-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_doctor_department_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Front Desk', 'Front Desk'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=100),
        ),
    ]
