# Generated by Django 6.0.1 on 2026-02-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Frontdesk', 'Frontdesk'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Administration', 'Administration'), ('Laboratory', 'Laboratory')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='core.department'),
        ),
    ]
