# Generated by Django 6.0.1 on 2026-02-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow Up'), ('EMERGENCY', 'Emergency'), ('ROUTINE_CHECKUP', 'Routine Checkup')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointments.slot'),
        ),
    ]
